import {
  AmazonLogo,
  AppleLogo,
  CanvaLogo,
  ClaudeLogo,
  CopilotLogo,
  CopyAILogo,
  CrunchyrollLogo,
  DisneyLogo,
  ElevenLabsLogo,
  GeminiLogo,
  GrokLogo,
  HBOMaxLogo,
  HuluLogo,
  JasperLogo,
  MidjourneyLogo,
  NetflixLogo,
  NotionLogo,
  OpenAILogo,
  OtterLogo,
  ParamountLogo,
  PeacockLogo,
  PerplexityLogo,
  RunwayLogo,
  SpotifyLogo,
  SynthesiaLogo,
  TidalLogo,
  TwitchLogo,
  YouTubeLogo,
} from '@/components/Logos'
import { Notification, Subscription } from '@/types/dummyData.types'

export const NOTIFICATIONS: Notification[] = [
  {
    id: 'notif_1',
    type: 'billing_reminder',
    title: 'Payment due in 3 days',
    body: 'Your OpenAI ChatGPT Plus subscription of $20.00 will be charged on May 1st.',
    subscriptionId: 'ai_1',
    subscriptionName: 'OpenAI ChatGPT Plus',
    amount: 20.0,
    timestamp: '2026-04-07T08:00:00Z',
    read: false,
  },
  {
    id: 'notif_2',
    type: 'payment_success',
    title: 'Payment confirmed ✓',
    body: 'Your Spotify Premium payment of $10.99 was processed successfully.',
    subscriptionId: 'str_2',
    subscriptionName: 'Spotify Premium',
    amount: 10.99,
    timestamp: '2026-04-06T14:32:00Z',
    read: false,
  },
  {
    id: 'notif_3',
    type: 'trial_expiring',
    title: 'Trial ending soon',
    body: 'Your Perplexity Pro free trial expires in 2 days. Add a payment method to continue.',
    subscriptionId: 'ai_6',
    subscriptionName: 'Perplexity Pro',
    amount: 20.0,
    timestamp: '2026-04-06T09:15:00Z',
    read: false,
  },
  {
    id: 'notif_4',
    type: 'price_change',
    title: 'Price update notice',
    body: 'Netflix Premium is increasing their price from $22.99 to $24.99 starting May 15th.',
    subscriptionId: 'str_1',
    subscriptionName: 'Netflix Premium',
    amount: 24.99,
    timestamp: '2026-04-05T11:00:00Z',
    read: true,
  },
  {
    id: 'notif_5',
    type: 'payment_failed',
    title: 'Payment failed',
    body: "We couldn't charge your card for ElevenLabs ($22.00). Please update your payment method.",
    subscriptionId: 'ai_10',
    subscriptionName: 'ElevenLabs',
    amount: 22.0,
    timestamp: '2026-04-05T07:45:00Z',
    read: true,
  },
  {
    id: 'notif_6',
    type: 'renewal_upcoming',
    title: 'Annual renewal coming up',
    body: 'Your Amazon Prime annual plan ($139.00) renews on January 10, 2027.',
    subscriptionId: 'str_3',
    subscriptionName: 'Amazon Prime',
    amount: 139.0,
    timestamp: '2026-04-04T16:20:00Z',
    read: true,
  },
  {
    id: 'notif_7',
    type: 'billing_reminder',
    title: 'Payment due tomorrow',
    body: 'GitHub Copilot ($10.00) will be charged to your card on file tomorrow.',
    subscriptionId: 'ai_7',
    subscriptionName: 'GitHub Copilot',
    amount: 10.0,
    timestamp: '2026-04-04T10:00:00Z',
    read: true,
  },
  {
    id: 'notif_8',
    type: 'subscription_cancelled',
    title: 'Subscription cancelled',
    body: 'Apple Music has been cancelled. Your access continues until April 22nd.',
    subscriptionId: 'str_7',
    subscriptionName: 'Apple Music',
    timestamp: '2026-04-03T13:10:00Z',
    read: true,
  },
  {
    id: 'notif_9',
    type: 'payment_success',
    title: 'Payment confirmed ✓',
    body: 'Google Gemini Advanced ($19.99) was charged successfully.',
    subscriptionId: 'ai_2',
    subscriptionName: 'Google Gemini Advanced',
    amount: 19.99,
    timestamp: '2026-04-03T08:05:00Z',
    read: true,
  },
  {
    id: 'notif_10',
    type: 'trial_expiring',
    title: 'Free trial ending',
    body: 'Hulu trial expires in 5 days. Your plan ($17.99/mo) starts automatically after.',
    subscriptionId: 'str_6',
    subscriptionName: 'Hulu',
    amount: 17.99,
    timestamp: '2026-04-02T11:30:00Z',
    read: true,
  },
]

export const AI_SUBSCRIPTIONS: Subscription[] = [
  {
    id: 'ai_1',
    name: 'OpenAI ChatGPT Plus',
    price: 20.0,
    billingCycle: 'monthly',
    nextBillingDate: '2026-05-01',
    icon: 'smart-toy',
    Logo: OpenAILogo,
    color: '#ECFDF5',
    bg: '#34D399',
    status: 'active',
  },
  {
    id: 'ai_2',
    name: 'Google Gemini Advanced',
    price: 19.99,
    billingCycle: 'monthly',
    nextBillingDate: '2026-04-15',
    icon: 'auto-awesome',
    Logo: GeminiLogo,
    color: '#EEF2FF',
    bg: '#818CF8',
    status: 'active',
  },
  {
    id: 'ai_3',
    name: 'Anthropic Claude Pro',
    price: 20.0,
    billingCycle: 'monthly',
    nextBillingDate: '2026-04-20',
    icon: 'psychology',
    Logo: ClaudeLogo,
    color: '#FFF7ED',
    bg: '#FB923C',
    status: 'active',
  },
  {
    id: 'ai_4',
    name: 'Grok Premium',
    price: 16.0,
    billingCycle: 'monthly',
    nextBillingDate: '2026-04-18',
    icon: 'public',
    Logo: GrokLogo,
    color: '#F1F5F9',
    bg: '#64748B',
    status: 'active',
  },
  {
    id: 'ai_5',
    name: 'Midjourney',
    price: 30.0,
    billingCycle: 'monthly',
    nextBillingDate: '2026-05-10',
    icon: 'brush',
    Logo: MidjourneyLogo,
    color: '#FDF2F8',
    bg: '#F472B6',
    status: 'active',
  },
  {
    id: 'ai_6',
    name: 'Perplexity Pro',
    price: 20.0,
    billingCycle: 'monthly',
    nextBillingDate: '2026-04-22',
    icon: 'search',
    Logo: PerplexityLogo,
    color: '#F0FDFA',
    bg: '#2DD4BF',
    status: 'trial',
  },
  {
    id: 'ai_7',
    name: 'GitHub Copilot',
    price: 10.0,
    billingCycle: 'monthly',
    nextBillingDate: '2026-04-11',
    icon: 'code',
    Logo: CopilotLogo,
    color: '#FAFAFA',
    bg: '#71717A',
    status: 'active',
  },
  {
    id: 'ai_8',
    name: 'Notion AI',
    price: 8.0,
    billingCycle: 'monthly',
    nextBillingDate: '2026-05-05',
    icon: 'description',
    Logo: NotionLogo,
    color: '#F8FAFC',
    bg: '#94A3B8',
    status: 'active',
  },
  {
    id: 'ai_9',
    name: 'RunwayML',
    price: 15.0,
    billingCycle: 'monthly',
    nextBillingDate: '2026-04-30',
    icon: 'movie-creation',
    Logo: RunwayLogo,
    color: '#F0FDF4',
    bg: '#4ADE80',
    status: 'active',
  },
  {
    id: 'ai_10',
    name: 'ElevenLabs',
    price: 22.0,
    billingCycle: 'monthly',
    nextBillingDate: '2026-05-12',
    icon: 'record-voice-over',
    Logo: ElevenLabsLogo,
    color: '#F5F3FF',
    bg: '#A78BFA',
    status: 'cancelled',
  },
  {
    id: 'ai_11',
    name: 'Jasper AI',
    price: 39.0,
    billingCycle: 'monthly',
    nextBillingDate: '2026-04-25',
    icon: 'edit-document',
    Logo: JasperLogo,
    color: '#FEFCE8',
    bg: '#FDE047',
    status: 'active',
  },
  {
    id: 'ai_12',
    name: 'Copy.ai',
    price: 36.0,
    billingCycle: 'monthly',
    nextBillingDate: '2026-05-02',
    icon: 'content-copy',
    Logo: CopyAILogo,
    color: '#F0F9FF',
    bg: '#38BDF8',
    status: 'trial',
  },
  {
    id: 'ai_13',
    name: 'Synthesia',
    price: 22.5,
    billingCycle: 'monthly',
    nextBillingDate: '2026-04-28',
    icon: 'video-camera-front',
    Logo: SynthesiaLogo,
    color: '#FFF1F2',
    bg: '#FB7185',
    status: 'active',
  },
  {
    id: 'ai_14',
    name: 'Otter.ai',
    price: 8.33,
    billingCycle: 'monthly',
    nextBillingDate: '2026-05-15',
    icon: 'graphic-eq',
    Logo: OtterLogo,
    color: '#ECFEFF',
    bg: '#22D3EE',
    status: 'active',
  },
  {
    id: 'ai_15',
    name: 'Canva Magic Studio',
    price: 12.99,
    billingCycle: 'monthly',
    nextBillingDate: '2026-04-19',
    icon: 'auto-fix-high',
    Logo: CanvaLogo,
    color: '#FAF5FF',
    bg: '#C084FC',
    status: 'active',
  },
]

export const STREAMING_SUBSCRIPTIONS: Subscription[] = [
  {
    id: 'str_1',
    name: 'Netflix Premium',
    price: 22.99,
    billingCycle: 'monthly',
    nextBillingDate: '2026-05-01',
    icon: 'play-circle',
    Logo: NetflixLogo,
    color: '#FEF2F2',
    bg: '#F87171',
    status: 'active',
  },
  {
    id: 'str_2',
    name: 'Spotify Premium',
    price: 10.99,
    billingCycle: 'monthly',
    nextBillingDate: '2026-04-15',
    icon: 'headphones',
    Logo: SpotifyLogo,
    color: '#F0FDF4',
    bg: '#4ADE80',
    status: 'active',
  },
  {
    id: 'str_3',
    name: 'Amazon Prime',
    price: 139.0,
    billingCycle: 'yearly',
    nextBillingDate: '2027-01-10',
    icon: 'local-shipping',
    Logo: AmazonLogo,
    color: '#F0F9FF',
    bg: '#38BDF8',
    status: 'active',
  },
  {
    id: 'str_4',
    name: 'HBO Max',
    price: 15.99,
    billingCycle: 'monthly',
    nextBillingDate: '2026-04-18',
    icon: 'movie',
    Logo: HBOMaxLogo,
    color: '#FAF5FF',
    bg: '#C084FC',
    status: 'active',
  },
  {
    id: 'str_5',
    name: 'Disney+',
    price: 13.99,
    billingCycle: 'monthly',
    nextBillingDate: '2026-04-20',
    icon: 'castle',
    Logo: DisneyLogo,
    color: '#EFF6FF',
    bg: '#60A5FA',
    status: 'active',
  },
  {
    id: 'str_6',
    name: 'Hulu',
    price: 17.99,
    billingCycle: 'monthly',
    nextBillingDate: '2026-05-05',
    icon: 'live-tv',
    Logo: HuluLogo,
    color: '#ECFDF5',
    bg: '#34D399',
    status: 'trial',
  },
  {
    id: 'str_7',
    name: 'Apple Music',
    price: 10.99,
    billingCycle: 'monthly',
    nextBillingDate: '2026-04-11',
    icon: 'music-note',
    Logo: AppleLogo,
    color: '#FDF2F8',
    bg: '#F472B6',
    status: 'cancelled',
  },
  {
    id: 'str_8',
    name: 'Apple TV+',
    price: 9.99,
    billingCycle: 'monthly',
    nextBillingDate: '2026-04-22',
    icon: 'tv',
    Logo: AppleLogo,
    color: '#F1F5F9',
    bg: '#94A3B8',
    status: 'active',
  },
  {
    id: 'str_9',
    name: 'YouTube Premium',
    price: 13.99,
    billingCycle: 'monthly',
    nextBillingDate: '2026-05-10',
    icon: 'smart-display',
    Logo: YouTubeLogo,
    color: '#FFF1F2',
    bg: '#FB7185',
    status: 'active',
  },
  {
    id: 'str_10',
    name: 'Paramount+',
    price: 11.99,
    billingCycle: 'monthly',
    nextBillingDate: '2026-04-30',
    icon: 'terrain',
    Logo: ParamountLogo,
    color: '#EEF2FF',
    bg: '#818CF8',
    status: 'active',
  },
  {
    id: 'str_11',
    name: 'Peacock Premium',
    price: 5.99,
    billingCycle: 'monthly',
    nextBillingDate: '2026-05-12',
    icon: 'emoji-nature',
    Logo: PeacockLogo,
    color: '#FFFBEB',
    bg: '#FBBF24',
    status: 'active',
  },
  {
    id: 'str_12',
    name: 'Crunchyroll',
    price: 9.99,
    billingCycle: 'monthly',
    nextBillingDate: '2026-04-25',
    icon: 'animation',
    Logo: CrunchyrollLogo,
    color: '#FFF7ED',
    bg: '#FB923C',
    status: 'active',
  },
  {
    id: 'str_13',
    name: 'Twitch Turbo',
    price: 11.99,
    billingCycle: 'monthly',
    nextBillingDate: '2026-05-02',
    icon: 'videogame-asset',
    Logo: TwitchLogo,
    color: '#F5F3FF',
    bg: '#A78BFA',
    status: 'active',
  },
  {
    id: 'str_14',
    name: 'Tidal',
    price: 10.99,
    billingCycle: 'monthly',
    nextBillingDate: '2026-04-28',
    icon: 'speaker',
    Logo: TidalLogo,
    color: '#ECFEFF',
    bg: '#22D3EE',
    status: 'active',
  },
  {
    id: 'str_15',
    name: 'Audible',
    price: 14.95,
    billingCycle: 'monthly',
    nextBillingDate: '2026-05-15',
    icon: 'menu-book',
    Logo: AmazonLogo,
    color: '#FEFCE8',
    bg: '#FDE047',
    status: 'trial',
  },
]
